spring:
  application:
    name: "estudo-spring-boot"
  data:
    mongodb:
      uri: "mongodb://localhost:27017/dinossauro_db" #"mongodb://user:password@localhost:27017/estudo_database"
  sleuth:
    enabled: true
    sampler:
      probability: 1.0

  zipkin:
    enabled: true
    service:
      name: "zipkin"
    baseUrl: "http://localhost:9411"
    sender:
      type: "web"

management:
  endpoints:
    web:
      exposure:
        include: "*"
